---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buy-ticket-service
  template:
    metadata:
      labels:
        app: buy-ticket-service
    spec:
      containers:
      - name: buy-ticket-service
        image: is213-concert-ticketing-buy-ticket-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5100
        command: ["python", "./buy_ticket.py"]

---
apiVersion: v1
kind: Service
metadata:
  name: buy-ticket-service
spec:
  selector:
    app: buy-ticket-service
  ports:
  - port: 5100
    targetPort: 5100
  type: ClusterIP