---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: is213-concert-ticketing-ticket-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        command: ["python", "./ticket.py"]

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
  - port: 5004
    targetPort: 5004
  type: ClusterIP