---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: is213-concert-ticketing-user-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5006
        command: ["python", "./user.py"]

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 5006
    targetPort: 5006
  type: ClusterIP